---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - 'min'

- name: Load OS specific variables
  ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Load host, hostgroup, location vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars/hostname={{ inventory_hostname }}.yml"
    - "vars/hostgroup={{ host_group }}.yml"
    - "vars/location={{ location }}.yml"
    - "vars/location=default.yml"

- name: No time configuration
  when: time_mgmt is regex('^([Nn]{1})([Oo]{0,1})$')
  ansible.builtin.include_tasks: no-time.yml

- name: Manage time
  when: time_mgmt is regex('^([Yy]{1})(([Ee][Ss]){0,1})$')
  block:
    - name: Timezone mgmt
      ansible.builtin.include_tasks: timezone.yml

    - name: Linux time mgmt
      when:
        ansible_facts['os_family'] == "RedHat" and
        ansible_facts['distribution_major_version'] >= "8"
      ansible.builtin.include_tasks: linux.yml

    - name: Solaris time mgmt
      when: ansible_facts['os_family'] == "Solaris"
      ansible.builtin.include_tasks: solaris.yml
...
